# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, max_length=30)),
                ('data_path', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, max_length=20, unique=True)),
            ],
        ),
    ]
