# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarepository',
            name='ip',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=30, null=True),
        ),
    ]
